import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ContactSidebar from "@/components/contact-sidebar";
import WhatsAppIcon from "@/components/whatsapp-icon";
import { ChatbotProvider } from "@/components/chatbot/ChatbotProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${geistMono.variable} antialiased`}>
        <ChatbotProvider>
          <Header />
          {children}
          <ContactSidebar />
          <WhatsAppIcon />
        </ChatbotProvider>
      </body>
    </html>
  );
}
