import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderWithCart from "@/components/header/HeaderWithCart";
import ContactSidebar from "@/components/contact-sidebar";
import WhatsAppIcon from "@/components/whatsapp-icon";
import { ChatbotProvider } from "@/components/chatbot/ChatbotProvider";
import ReduxProvider from "@/components/providers/ReduxProvider";
import { CartProvider } from "@/components/cart/CartProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <CartProvider>
            <ChatbotProvider>
              <HeaderWithCart />
              {children}
              <ContactSidebar />
              <WhatsAppIcon />
            </ChatbotProvider>
          </CartProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
